version: "3.9"

services:
  db:
    image: postgres:17
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: root
      POSTGRES_DB: skillcase
    ports:
      - "5000:5432"  
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: node_app
    restart: always
    depends_on:
      - db
    ports:
      - "3000:3000"
    environment:
      # Optional: pass Postgres connection info to app
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: user
      DB_PASSWORD: root
      DB_NAME: skillcase

volumes:
  db_data:
