version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: skillcase
      MYSQL_USER: user
      MYSQL_PASSWORD: root
    ports:
      - "5000:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    build: .
    container_name: node_app
    restart: always
    depends_on:
      - db
    ports:
      - "3000:3000"

volumes:
  db_data:
